export const API_ROUTES = {
    SIGN_IN: '/sign-in',
    LOGOUT: '/logout',
    DASHBOARD: '/dashboard',
    FORGOT_PASSWORD: {
        VALIDATE_EMAIL: '/forgot-password/send-email',
        RESET_PASSWORD: '/forgot-password/reset-password',
    },
    GET_FILE: '/files/download',
    SIGN_URL: '/files/sign-url',
    CHANGE_PASSWORD: '/users/change-password',
    SORT_FILES: '/files/sort',
    UPDATE_USER: '/me',
    GET_UTIL_DATA: '/util-data',
    NOTIFICATIONS: '/users/notifications',
    CLIENTS: {
        LIST: '/clients',
        CREATE: '/clients',
        UPDATE: '/clients/{id}',
        BASIC_LIST: '/clients/basic-list',
        STATS: '/clients/{id}/stats',
        DETAIL: '/clients/{id}',
        METRICS: '/clients/metrics',
        GET_NETWORK: '/clients/{id}/network',
        SET_PLAN: '/clients/{id}/set-plan',
        SET_TEMPLATE: '/clients/{id}/set-template',
        UPDATE_NETWORK: '/clients/{id}/update-network',
    },
    PLANS: {
        LIST: '/plans',
        DETAIL: '/plans/{id}',
        UPDATE: '/plans/{id}',
    },
    TEMPLATES: {
        LIST: '/templates',
        CREATE: '/templates',
        DETAIL: '/templates/{id}',
        UPDATE: '/templates/{id}',
        DELETE: '/templates/{id}',
        STATS: '/templates/stats',
        UPLOAD_ASSETS: '/templates/{id}/upload-assets',
        GET_UPLOAD_ASSETS_URL: '/templates/{id}/upload-assets-url',
        UPLOAD_TEMPLATE: '/templates/{id}/upload-template'
    },
    PERMISSIONS: {
        GET_ALL_ACCESS: '/roles/accesses',
        SET_PERMISSIONS_BY_ROLE: '/roles/{roleKey}/permissions',
    },
    VERIFICATION_TEMPORARY_CODE: '/verification-temporary-code',
    TASKS: {
        LIST: '/tasks',
        CREATE: '/tasks',
        DETAIL: '/tasks/{id}',
        UPDATE: '/tasks/{id}',
        DELETE: '/tasks/{id}',
        STATS: '/tasks/stats',
        GET_ACTIVITY: '/tasks/{id}/activity',
        STORE_COMMENT: '/tasks/{id}/comment',
        STORE_ATTACHMENTS: '/tasks/{id}/attachments',
        DELETE_ATTACHMENT: '/tasks/{id}/attachments/{attachmentId}',
        DOWNLOAD_FILE: '/tasks/{id}/attachments/{fileId}/download',
        GET_FILES: '/tasks/{id}/attachments',
    },
    TRAININGS: {
        LIST: '/trainings',
        CREATE: '/trainings',
        UPDATE: '/trainings/{id}',
        DELETE: '/trainings/{id}',
        DETAIL: '/trainings/{id}',
        ATTACH_FILE: '/trainings/{id}/attach-file',
    },
    REPORTS: {
        GET_UPLOADS: '/reports/uploads',
        UPLOAD: '/reports/upload',
    }
}